# ---------------------------------------------------------------------------
# Orderer : 검증된 트랜잭션들을 이용해 최종적으로 블록생성
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost