# ---------------------------------------------------------------------------
#  peer nodes 관리 
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Template"
    # 기본적으로 0에서 Count-1 까지 peer0, peer1 ... 로 표시
    # 노드 수(Count), 시작(Start)을 재정의할 수 있다.
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      SANS:
        - localhost
        # Start: 5
        # Hostname: {{.Prefix}}{{.Index}} # default
    Users: 
      Count: 1    
      # 사용자 계정 수 