# ---------------------------------------------------------------------------
# docker-compose : couchDB container 
# CA는 나중에!!!!! 
# ---------------------------------------------------------------------------
version: '2'

networks:
  test:

services:
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    # couchDB 사용자 및 암호 설정
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
   
    ports:
      - "5984:5984"
    networks:
      - test

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
  
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    
    ports:
      - "7984:5984"
    networks:
      - test